export const categories = [
    {
        id: 1,
        name:'Alojamiento',
        color: '#C62828',
        second_color: '#D32F2F',
        third_color: '#FFCDD2',
        icon: 'home-city-outline',
        value: 0,
    },
    {
        id: 2,
        name:'Transporte',
        color: '#00695C',
        second_color: '#00796B',
        third_color: '#B2DFDB',
        icon: 'train-car',
        value: 0,
    },
    {
        id: 3,
        name:'Facturas',
        color: '#6A1B9A',
        second_color: '#7B1FA2',
        third_color: '#E1BEE7',
        icon: 'file-document-outline',
        value: 0,
    },
    {
        id: 4,
        name:'Gastos Personales',
        color: '#1565C0',
        second_color: '#1976D2',
        third_color: '#BBDEFB',
        icon: 'account-convert',
        value: 0,
    },
    {
        id: 5,
        name:'Comida',
        color: '#FF8F00',
        second_color: '#FFA000',
        third_color: '#FFECB3',
        icon: 'food-fork-drink',
        value: 0,
    },
    {
        id: 6,
        name:'Créditos',
        color: '#4E342E',
        second_color: '#5D4037',
        third_color: '#D7CCC8',
        icon: 'credit-card-multiple-outline',
        value: 0,
    },
];